## NumPY Cheat Sheet

Useful NumPy functionality and methods

In [1]:
import numpy as np

In [2]:
# create an ndarray from a list
l = [1,2,3,4,5,6,7,8,9]
np.array(l)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# creating an array using arange
np.arange(0,100, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [4]:
# create an ndarray of zeros
np.zeros(100)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [5]:
# create a matrix of zeros given specific dimensions
np.zeros((2, 10))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [6]:
# creating a matrix of 1's givene specific dimensions
np.ones((2,2))

array([[ 1.,  1.],
       [ 1.,  1.]])

In [7]:
# create a linearly spaced array
np.linspace(0, 25, 5)

array([  0.  ,   6.25,  12.5 ,  18.75,  25.  ])

In [8]:
# generate random numbers
np.random.randint(0, 10)

7

In [9]:
# create a random index of a specified dimension
np.random.randint(0, 100, (5,5))

array([[58, 42, 76, 77, 18],
       [65, 58, 22, 57, 46],
       [ 1,  3, 45, 14, 76],
       [ 6, 50, 35,  8, 70],
       [77, 26, 36, 34, 73]])

In [10]:
# seed random values
np.random.seed(100)
np.random.randint(0, 100, 10)

array([ 8, 24, 67, 87, 79, 48, 10, 94, 52, 98])

In [11]:
arr = np.random.randint(0, 1000, 100)
arr

array([ 53, 578, 738, 526, 802, 752, 280, 655, 228, 875, 316, 570, 912,
       507, 649,  93,  86, 386, 667, 876, 900, 415, 897, 141, 757, 723,
       612,   4, 603, 955, 835, 135,  49, 431, 705, 317, 782, 695, 967,
       763, 336,   2, 889, 617, 478, 403, 994,  63, 181, 283, 824, 238,
       369, 926, 944, 303, 679, 877, 806, 172, 274, 192, 952, 930, 437,
       714, 273, 584, 525, 618,  30,  17,  53,  68, 946, 488, 347, 475,
       979, 693, 846,   0,  13, 185, 460, 362, 131, 582, 643, 212, 719,
       394, 215, 502, 495, 956, 643, 873, 176, 180])

In [12]:
#find the max and min
arr.max()

994

In [13]:
# find the min
arr.min()

0

In [14]:
# find the avearge
arr.mean()

508.00999999999999

In [15]:
# find index of min value
arr.argmin()

81

In [16]:
# find index of max value
arr.argmax()

46

In [17]:
# reshape an array 
arr.reshape(2, 50)

array([[ 53, 578, 738, 526, 802, 752, 280, 655, 228, 875, 316, 570, 912,
        507, 649,  93,  86, 386, 667, 876, 900, 415, 897, 141, 757, 723,
        612,   4, 603, 955, 835, 135,  49, 431, 705, 317, 782, 695, 967,
        763, 336,   2, 889, 617, 478, 403, 994,  63, 181, 283],
       [824, 238, 369, 926, 944, 303, 679, 877, 806, 172, 274, 192, 952,
        930, 437, 714, 273, 584, 525, 618,  30,  17,  53,  68, 946, 488,
        347, 475, 979, 693, 846,   0,  13, 185, 460, 362, 131, 582, 643,
        212, 719, 394, 215, 502, 495, 956, 643, 873, 176, 180]])

In [18]:
# create a matrix from a range
matrix = np.arange(0,100).reshape(10,10)
matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [19]:
# grab an element from the matrix using matrix notation
matrix[4,4]

44

In [20]:
# slice matrix by column
matrix[:,0]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [21]:
# slice matrix by row
matrix[0,:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# slice sections of a matrix
matrix[1:4, 1:4]

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [23]:
# masking
predicate = matrix > 90
matrix[predicate]

array([91, 92, 93, 94, 95, 96, 97, 98, 99])

In [24]:
# iterate over array
A = matrix
for element in A[0]:
    print(element)

0
1
2
3
4
5
6
7
8
9


## Linear Algebrea Methods

In [25]:
v1 = np.arange(0, 5)
v1

array([0, 1, 2, 3, 4])

In [26]:
# scalar multiplication
v1 * 2

array([0, 2, 4, 6, 8])

In [27]:
# addition
v1 + 2

array([2, 3, 4, 5, 6])

In [28]:
A = np.arange(0, 25).reshape(5,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
# matrix multiplication
np.dot(A, v1) # can also do A * v1

array([ 30,  80, 130, 180, 230])

In [30]:
np.dot(v1, v1)

30

In [31]:
# create a matrix from a list
l = [[1,2,3],
    [4,5,6],
    [7,8,9]]
M = np.matrix(l)
M

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [32]:
# transpose matrix
M.T

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [34]:
# slice a matrix by column
M[:,:1]

matrix([[1],
        [4],
        [7]])

In [36]:
# slice a matrix by row
M[:1, :]

matrix([[1, 2, 3]])