In [9]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

In [2]:
data = np.random.randint(0,100,(10,2))
data

array([[32,  8],
       [ 9, 52],
       [21, 58],
       [48, 96],
       [87, 74],
       [35, 71],
       [55, 54],
       [73, 86],
       [87, 64],
       [36, 51]])

In [3]:
# normalize data
scaler_model = MinMaxScaler()
scaler_model.fit(data)
scaler_model.transform(data)

/usr/local/lib/python3.6/site-packages/sklearn/utils/validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[ 0.29487179,  0.        ],
       [ 0.        ,  0.5       ],
       [ 0.15384615,  0.56818182],
       [ 0.5       ,  1.        ],
       [ 1.        ,  0.75      ],
       [ 0.33333333,  0.71590909],
       [ 0.58974359,  0.52272727],
       [ 0.82051282,  0.88636364],
       [ 1.        ,  0.63636364],
       [ 0.34615385,  0.48863636]])

In [4]:
# normalize data in one step
scaler_model.fit_transform(data)

/usr/local/lib/python3.6/site-packages/sklearn/utils/validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[ 0.29487179,  0.        ],
       [ 0.        ,  0.5       ],
       [ 0.15384615,  0.56818182],
       [ 0.5       ,  1.        ],
       [ 1.        ,  0.75      ],
       [ 0.33333333,  0.71590909],
       [ 0.58974359,  0.52272727],
       [ 0.82051282,  0.88636364],
       [ 1.        ,  0.63636364],
       [ 0.34615385,  0.48863636]])

In [8]:
# split data into training set
frame_data = np.random.randint(0,101,(50,4))
df = pd.DataFrame(data=frame_data, columns=['Feature 1', 'Feature 2', 'Feature 3', 'Label'])
df.head()

Feature 1  Feature 2  Feature 3  Label
0         44         56         98     16
1         39         49          8     69
2         32         34         72     13
3         54         84          0     21
4         60         30         73     37

In [11]:
# create our X and y values from the frame
X = df[['Feature 1', 'Feature 2', 'Feature 3']]
y = df['Label']

In [12]:
# split our data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size=0.3, 
                                                    random_state=100)