In [1]:
import tensorflow as tf

/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [3]:
# constant
c1 = tf.constant('Hello ')
c2 = tf.constant("TensorFlow")

In [4]:
with tf.Session() as sess:
    result = sess.run(c1 + c2)

In [5]:
result

b'Hello TensorFlow'

In [6]:
# another constant example
four = tf.constant(4)
five = tf.constant(5)

with tf.Session() as sess:
    result = sess.run(four + five)
result

9

In [7]:
# create a matrix
M = tf.fill((4,4), 10)
M

<tf.Tensor 'Fill:0' shape=(4, 4) dtype=int32>

In [9]:
# create a tensor prefilled with zeros
Z = tf.zeros((4,4))
Z

<tf.Tensor 'zeros:0' shape=(4, 4) dtype=float32>

In [10]:
# create a tensor prefilled with ones
O = tf.ones((4,4))
O

<tf.Tensor 'ones:0' shape=(4, 4) dtype=float32>

In [12]:
# create a random tensor using a normal distribution
rand_norm = tf.random_normal((4,4), mean=0, stddev=1.0)
rand_norm

<tf.Tensor 'random_normal_1:0' shape=(4, 4) dtype=float32>

In [13]:
# create a random tensor using a uniform distribution
rand_uniform = tf.random_uniform((4,4), minval=0, maxval=1)
rand_uniform

<tf.Tensor 'random_uniform:0' shape=(4, 4) dtype=float32>

In [14]:
# run our tensors defined above in an interactive session (notebok only)
ops = [M, Z, O, rand_norm, rand_uniform]

sess = tf.InteractiveSession()
for op in ops:
    print(sess.run(op))
    print('\n')

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


[[-0.1469361   1.95909607  0.78333396 -0.69428408]
 [ 1.39792418 -1.1961863   0.23278463 -0.51047039]
 [-0.03999763  1.43181241  0.90890205 -0.6324358 ]
 [ 1.24765313 -0.20626073  0.15754466 -0.94608051]]


[[ 0.23219597  0.58042955  0.45465028  0.98394966]
 [ 0.81061506  0.38696253  0.79134607  0.82774019]
 [ 0.86988723  0.79212546  0.55334437  0.16402829]
 [ 0.81040668  0.66080356  0.34474862  0.82460701]]




In [17]:
# get the shape of a tensor
a = tf.constant([[1,2], [3,4]])
b = tf.constant([[10], [100]])

a.get_shape(), b.get_shape()

(TensorShape([Dimension(2), Dimension(2)]),
 TensorShape([Dimension(2), Dimension(1)]))

In [18]:
# multiply two tensors
result = tf.matmul(a,b)

sess.run(result)

array([[210],
       [430]], dtype=int32)

In [21]:
# creating nodes of a TensforFlow graph (two constants and one computation node)
node_1 = tf.constant(100)
node_2 = tf.constant(200)
node_3 = node_1 + node_2

with tf.Session() as sess:
    result = sess.run(node_3)

print(node_3)
result

Tensor("add_4:0", shape=(), dtype=int32)


300

In [22]:
# variables
rand_tensor = tf.random_uniform((4,4),0,1)
sample_var = tf.Variable(initial_value=rand_tensor)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    result = sess.run(sample_var)
result

array([[ 0.89583421,  0.16479731,  0.95974827,  0.60598671],
       [ 0.93325877,  0.82408035,  0.03495336,  0.52427411],
       [ 0.92457974,  0.35486507,  0.58409083,  0.8607645 ],
       [ 0.36333513,  0.2356627 ,  0.73056483,  0.42743778]], dtype=float32)

In [ ]:
# placeholders
sample_placehodler = tf.placeholder(tf.float32, shape=(None, 10))